"use client";
import { useState } from "react";
import { ArrowRight, Check, Clock3, Layers3, MessageSquareWarning, Quote, ShieldCheck, Siren, WalletCards, Zap } from "lucide-react";
import LeadCapture from "@/components/LeadCapture";
import ChatWidget from "@/components/ChatWidget";
import Footer from "@/components/Footer";

const steps=[["01","Tell us what is happening","Start with your name and phone, then add only what you want to share."],["02","We review the pressure","Organize withdrawals, active positions, and the operating costs being squeezed."],["03","A person follows up","A team member reviews the request before reaching out to discuss the situation."],["04","Choose the next move","Use the conversation to understand realistic options and what to prepare next."]];
const reviews=[
{name:"Restaurant operator",role:"Hospitality · sample review",image:"https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=700",quote:"I needed a fast way to explain the situation without another giant application. The first step was simple."},
{name:"Contractor",role:"Construction · sample review",image:"https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=700",quote:"The process was direct and calm. I could get the facts organized before talking through options."},
{name:"Retail owner",role:"Retail · sample review",image:"https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=700",quote:"The site felt urgent without feeling pushy. That mattered because I was already dealing with enough pressure."}
];
export default function Home(){const [open,setOpen]=useState(false);return <main>
<header className="nav"><a className="brand" href="#top"><b>24/7</b> MCA RELIEF</a><nav><a href="#solutions">Situations</a><a href="#process">How it works</a><a href="#stories">Stories</a><a href="/insights">Resources</a></nav><button onClick={()=>setOpen(true)}>Get help now</button></header>
<section id="top" className="hero"><div className="pulse"/><div className="wrap heroGrid"><div className="heroCopy"><span className="kicker"><Siren/> REQUEST HELP ANYTIME</span><h1>Payments do not wait. <em>Neither should your options.</em></h1><p>A fast, confidential first step for business owners dealing with MCA payment pressure. Share the basics, let a real person review the request, and move from reaction to a clearer plan.</p><div className="actions"><button onClick={()=>setOpen(true)}>Get help now <ArrowRight/></button><a href="#process"><Clock3/> See the process</a></div><div className="bullets"><span><Check/>Name + phone only required</span><span><Check/>Business-purpose inquiries</span><span><Check/>No guaranteed outcomes</span></div></div><LeadCapture title="Get immediate help" button="Request my review" source="hero"/></div><div className="band"><div><strong>24/7</strong><span>Website access</span></div><div><ShieldCheck/><span>Confidential intake</span></div><div><Zap/><span>Fast first step</span></div><div><Check/><span>No obligation to submit</span></div></div></section>
<section id="solutions" className="section light"><div className="wrap"><div className="sectionTitle"><span>RECOGNIZE THE PRESSURE</span><h2>The operating day should not revolve around the next withdrawal.</h2></div><div className="pressureGrid"><article><Zap/><h3>Daily ACH squeeze</h3><p>Withdrawals are arriving before payroll, inventory, taxes, or essential vendors are funded.</p></article><article><Layers3/><h3>Multiple advances</h3><p>Several positions are pulling from the same revenue and hiding the true weekly burden.</p></article><article><WalletCards/><h3>Cash-flow mismatch</h3><p>Revenue changed, but the payment cadence did not. The business needs breathing room to operate.</p></article><article><MessageSquareWarning/><h3>Escalating contact</h3><p>Calls and notices are taking attention away from running the company and serving customers.</p></article></div></div></section>
<section id="process" className="section dark"><div className="wrap"><div className="sectionTitle invert"><span>HOW IT WORKS</span><h2>Fast enough for urgency. Structured enough for trust.</h2></div><div className="steps">{steps.map((s,i)=><article key={s[0]}><span>{s[0]}</span><div className="node">{i+1}</div><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></div></section>
<section id="stories" className="section stories"><div className="wrap"><div className="sectionTitle"><span>BUSINESS-OWNER STORIES</span><h2>Urgency does not need high-pressure marketing.</h2><p>Sample review layouts for staging. Replace names, photos, and review copy with client-approved information before production.</p></div><div className="reviewGrid">{reviews.map(r=><article key={r.name}><img src={r.image} alt="Business owner"/><div><Quote/><p>“{r.quote}”</p><strong>{r.name}</strong><span>{r.role}</span></div></article>)}</div></div></section>
<section className="close"><div className="wrap closeGrid"><div><span>READY WHEN YOU ARE</span><h2>Do not wait for the pressure to get louder.</h2><p>Request a private review now. A real person can follow up after the information is reviewed.</p></div><button onClick={()=>setOpen(true)}>Start my review <ArrowRight/></button></div></section>
<Footer/><ChatWidget/>{open&&<div className="modalBack" onClick={()=>setOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modalX" onClick={()=>setOpen(false)}>×</button><LeadCapture title="Start a private review" button="Send my request" source="modal"/></div></div>}</main>}
