import { notFound } from "next/navigation";
const pages:any={
'privacy-policy':['Privacy Policy',['We may collect information you submit through forms or chat, such as your name, phone number, optional business details, page source, and technical information used for security and analytics when enabled.','Information may be used to respond to inquiries, operate the website, prevent abuse, measure site performance, and deliver leads to authorized service providers or CRM systems.','Do not submit confidential legal documents or sensitive personal information unless the company has approved a secure process for receiving them.']],
'terms-of-use':['Terms of Use',['This website is provided for general business information and inquiry purposes. Using the site does not enroll a business in a service or guarantee that any service will be offered.','Website content is not legal, tax, accounting, or financial advice. You are responsible for evaluating your own agreements and business decisions with appropriate professional advisers.','The site may contain third-party services, links, or analytics tools. Availability and content may change without notice.']],
'legal-disclaimer':['Legal Disclaimer',['24/7 MCA Relief is not a law firm, lender, government agency, or court and does not provide legal representation through this website.','No statement on this site guarantees settlement, restructuring, payment reduction, creditor participation, timing, or any other result. Outcomes vary based on agreements, business facts, third parties, and applicable law.','Staging testimonials, names, photos, and illustrative examples must be replaced with client-approved material before production use.']],
'communication-consent':['Communication Consent',['When you affirmatively check the contact-consent box and submit your information, you authorize calls and text messages regarding your business inquiry at the number you provided, including automated technology where permitted.','Consent is not a condition of purchase. Message and data rates may apply. Message frequency varies. You may reply STOP to opt out of texts and HELP for assistance.']],
'cookie-policy':['Cookie Policy',['The staging website does not need advertising cookies to accept a lead. If analytics or advertising tools are enabled later, the site should present appropriate consent controls before optional tracking is activated.','Essential technical storage may be used for security, preferences, and normal website operation.']]
};
export default async function Legal({params}:{params:Promise<{legal:string}>}){const{legal}=await params;const p=pages[legal];if(!p)notFound();return <main className="articlePage"><div className="wrap narrow"><a className="back" href="/">← Home</a><h1>{p[0]}</h1>{p[1].map((x:string)=><p key={x}>{x}</p>)}<p><strong>Staging draft:</strong> final language should be reviewed against the client’s actual services, states served, vendors, and communication practices before launch.</p></div></main>}
